version: '3'
services:
  db:
    user: root
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: brasileirao-sqlserver
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=some(!)Password
    # espelhamento de pastas entre container e máquina local
    volumes:
      # lado direito é o pasta do container
      # lado esquerdo pasta da nossa máquina
      - ./volumes/data:/var/opt/mssql/data