POST https://localhost:5001/users HTTP/1.1
content-type: application/json

{
    "name": "Jhon Wick",
    "profile": 1,
    "password": "",
    "email": "jhon.wick@gmail.com"
}

POST https://localhost:5001/auth/login HTTP/1.1
content-type: application/json

{
    "email": "jhon.wick@gmail.com",
    "password": "123456"
}

GET https://localhost:5001/teams HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ikpob24gV2ljayIsInJvbGUiOiJTdXBwb3J0ZXIiLCJuYmYiOjE2MTI3MzY1MDEsImV4cCI6MTYxMjczNjYyMSwiaWF0IjoxNjEyNzM2NTAxfQ.fNryTDxrVJFpz4eDyL8ZPn0H0I_S8O7XotAXHLFTSxQ


GET https://localhost:5001/users/me HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Ikpob24gV2ljayIsIm5hbWVpZCI6IjU0NmY3ODIyLTBiMWYtNGZlOS1hNjI0LWQ4ZDEwNTBhYWJjYyIsInJvbGUiOiJTdXBwb3J0ZXIiLCJuYmYiOjE2MTI3MzgwOTMsImV4cCI6MTYxMjczODIxMywiaWF0IjoxNjEyNzM4MDkzfQ.L0-NuLOuD2h0MSjwinRcIVCW-ewr-wh6X6wONJedZiE

